-- =====================================================
-- TODOS OS PRODUTOS DO CATÁLOGO NEMA'S WAY
-- Com 50% de desconto automático para cadastrados
-- =====================================================

-- Este arquivo contém TODOS os produtos identificados no catálogo
-- O desconto de 50% será aplicado automaticamente pelo trigger

INSERT INTO public.supplements (external_id, name, brand, category, active_ingredients, recommended_dosage, benefits, contraindications, description, original_price, stock_quantity, is_approved, image_url, tags)
VALUES
  -- PRODUTOS DE BELEZA E CUIDADOS PESSOAIS
  ('SOS_UNHAS', 'SOS UNHAS', 'Nema''s Way', 'beleza', ARRAY['Óleo de Girassol Ozonizado'], 'Aplicar sobre unhas limpas e secas', ARRAY['Fortalece unhas frágeis e quebradiças', 'Combate fungos e previne infecções', 'Estimula crescimento saudável', 'Protege e nutre com óleo ozonizado'], ARRAY[], 'Base fortalecedora e antifúngica ozonizada. O poder do ozônio unido ao mix de vitaminas para suas unhas!', 49.90, 200, true, NULL, ARRAY['unhas', 'fortalecedor', 'antifungico', 'ozonizado']),
  
  ('COLAGENO_ACIDO_HIALURONICO', 'Colágeno com Ácido Hialurônico', 'Nema''s Way', 'beleza', ARRAY['Colágeno Verisol', 'Ácido Hialurônico', 'Vitamina C', 'Biotina'], '2 scoops com água pela manhã', ARRAY['Melhora elasticidade e firmeza da pele', 'Hidratação profunda da pele', 'Fortalecimento de unhas e cabelos', 'Ação antioxidante', 'Saúde das articulações'], ARRAY[], 'Colágeno Verisol com Ácido Hialurônico, Vitamina C e Biotina. Sabor Frutas Vermelhas. Zero açúcares. 200g rende 20 porções.', 299.90, 150, true, NULL, ARRAY['colageno', 'acido_hialuronico', 'pele', 'articulacoes', 'verisol']),
  
  ('BVB_CALCIO', 'BVB Cálcio Concha Ostra', 'Nema''s Way', 'minerais', ARRAY['Cálcio de Concha de Ostra 600mg'], '2 cápsulas antes de dormir', ARRAY['Fortalecimento ósseo', 'Coagulação sanguínea adequada', 'Suporte muscular', 'Sistema nervoso equilibrado', 'Divisão celular', 'Energia celular'], ARRAY['Alergia a frutos do mar'], 'O único cálcio natural de concha de ostra que fortalece ossos, melhora função muscular e apoia saúde do sistema nervoso.', 99.90, 180, true, NULL, ARRAY['calcio', 'ossos', 'concha_ostra', 'minerais']),
  
  ('LIPOWAY', 'Lipo Way', 'Nema''s Way', 'emagrecimento', ARRAY['Cafeína', 'Chá Verde', 'L-Carnitina'], '02 Cápsulas ao dia', ARRAY['Queima gordura e é termogênico', 'Fornece energia', 'Acelera metabolismo', 'Auxilia no ganho de massa magra'], ARRAY['Hipertensão', 'Insônia'], 'Transforme seu corpo com Lipoway. O segredo para queimar gordura, ganhar energia e acelerar o metabolismo. 60 cápsulas de 1.400mg.', 149.90, 140, true, NULL, ARRAY['emagrecimento', 'termogenico', 'gordura', 'metabolismo']),
  
  ('BVB_SB', 'BVB SB', 'Nema''s Way', 'emagrecimento', ARRAY['Antioxidantes', 'Fibras', 'Nutrientes essenciais'], '2 cápsulas 30 minutos antes do almoço', ARRAY['Promove saciedade prolongada (controle apetite)', 'Reduz absorção de gorduras e carboidratos', 'Controle glicêmico e lipídico', 'Estimula metabolismo e queima de gordura', 'Ação antioxidante e anti-inflamatória', 'Favorece funcionamento intestinal', 'Suporte à saúde da pele, articulações e imunidade'], ARRAY[], 'Queime gordura, domine seu metabolismo. Um verdadeiro escudo para imunidade, pele, articulações e bem-estar. 60 cápsulas de 600mg.', 149.90, 160, true, NULL, ARRAY['emagrecimento', 'fibras', 'antioxidante', 'apetite']),
  
  ('WINNER_OLEO_PERNAS', 'Winner Óleo para Pernas Ozonizado', 'Nema''s Way', 'topico', ARRAY['Castanha da Índia', 'Óleo de Calêndula', 'Óleo de Amêndoas', 'Óleo Semente de Uva', 'Cânfora', 'Mentol'], 'Aplicar nas pernas com movimentos circulares. Diariamente após banho ou cansaço', ARRAY['Ativa circulação sanguínea', 'Alivia sensação de peso e cansaço', 'Devolve frescor imediato', 'Ação vasoprotetora', 'Favorece vitalidade das pernas'], ARRAY[], 'O campeão voltou desde 1986. Formulado para oferecer alívio imediato e cuidado contínuo. 120ml.', 79.90, 180, true, NULL, ARRAY['pernas', 'circulacao', 'ozonizado', 'topico']),
  
  ('VITAMINA_K2', 'Vitamina K2', 'Nema''s Way', 'vitaminas', ARRAY['Vitamina K2 (MK-7)'], '2 cápsulas na hora do almoço', ARRAY['Saúde óssea', 'Proteção cardiovascular', 'Sinergia com vitamina D3', 'Prevenção de osteoporose'], ARRAY[], 'O GPS que o corpo precisa. A vitamina K2 direciona o cálcio para os ossos e impede acúmulo nas artérias. 60 cápsulas de 600mg.', 99.90, 200, true, NULL, ARRAY['vitamina_k2', 'ossos', 'cardiovascular', 'calcio']),
  
  ('FRESH_GLOW_CREME', 'Fresh Glow Creme Corporal', 'Nema''s Way', 'beleza', ARRAY['Ozônio', 'Colágeno', 'Elastina'], 'Uso Diário', ARRAY['Ação purificadora e regenerativa', 'Prevenção do envelhecimento', 'Hidratação e maciez', 'Firmeza e elasticidade'], ARRAY[], 'Combinação perfeita de ozônio, colágeno e elastina para firmeza, elasticidade e hidratação profunda. 200g.', 99.99, 170, true, NULL, ARRAY['creme_corporal', 'ozonizado', 'colageno', 'elastina']),
  
  ('VITAMINA_C_400MG', 'Vitamina C', 'Nema''s Way', 'vitaminas', ARRAY['Ácido Ascórbico 400mg'], '01 Cápsula ao dia', ARRAY['Rejuvenescimento da pele', 'Promoção de longevidade', 'Reforço do sistema imunológico', 'Proteção contra radicais livres', 'Combate a vírus e bactérias'], ARRAY['Cálculos renais'], 'Segredo para rejuvenescimento, longevidade e imunidade. Mais longevidade para sua vida. 30 cápsulas de 400mg (250mg por cápsula).', 49.90, 250, true, NULL, ARRAY['vitamina_c', 'antioxidante', 'imunidade', 'pele']),
  
  ('FRESH_GLOW_LOCAO', 'Fresh Glow Loção Adstringente', 'Nema''s Way', 'beleza', ARRAY['Alantoína', 'Aloe Vera', 'D-Pantenol', 'Ácido de Frutas', 'Vitamina E'], 'Uso Diário', ARRAY['Esfoliante natural (remove células mortas)', 'Aumenta elasticidade da pele', 'Propriedades calmantes', 'Limpa e tonifica profundamente'], ARRAY[], 'Combina ativos potentes para limpar, purificar e tonificar profundamente a pele. Ozonizado. 250ml.', 99.90, 160, true, NULL, ARRAY['adstringente', 'facial', 'ozonizado', 'esfoliante']),
  
  ('BVB_COLEST', 'BVB Colest', 'Nema''s Way', 'cardiovascular', ARRAY['Proantocianidinas de Cranberry'], '2 cápsulas na hora do almoço', ARRAY['Saúde do trato urinário (prevenção infecções)', 'Ação antioxidante', 'Auxílio na redução do colesterol ruim (LDL)', 'Apoio ao sistema imunológico', 'Manutenção da boa circulação'], ARRAY[], 'Fonte de Proantocianidinas Cranberry. Contribui para proteção do trato urinário, equilíbrio do colesterol e saúde cardiovascular. 60 cápsulas de 600mg.', 129.90, 150, true, NULL, ARRAY['cranberry', 'trato_urinario', 'colesterol', 'antioxidante']),
  
  ('FRESH_GLOW_SABONETE', 'Fresh Glow Sabonete Facial', 'Nema''s Way', 'higiene', ARRAY['Extrato de Kiwi', 'Ozônio', 'Aloe Vera'], 'Uso Diário', ARRAY['Limpeza profunda e revitalização', 'Ação purificadora e renovadora', 'Hidratação e suavização', 'Desobstrução dos poros', 'Combate radicais livres'], ARRAY[], 'Fórmula enriquecida com extrato de kiwi, ozônio e aloe vera. Frescor e luminosidade em cada limpeza. Ozonizado. 200g.', 99.99, 200, true, NULL, ARRAY['sabonete_facial', 'ozonizado', 'kiwi', 'aloe_vera']),
  
  ('BVB_D3K2', 'BVB D3K2', 'Nema''s Way', 'vitaminas', ARRAY['Vitamina D3', 'Vitamina K2'], '02 Cápsulas ao dia', ARRAY['Combate doenças autoimunes e do coração', 'Contribui para dentes saudáveis e previne calvície', 'Importante para coagulação sanguínea', 'Melhora função hormonal', 'Previne infarto'], ARRAY[], 'A fórmula perfeita para sua saúde. Renova saúde, melhora imunidade e previne calvície. 60 cápsulas de 700mg.', 149.90, 180, true, NULL, ARRAY['vitamina_d3', 'vitamina_k2', 'imunidade', 'calvicie']),
  
  ('SD_ARTRO', 'SD Artro', 'Nema''s Way', 'articulacoes', ARRAY['Magnésio', 'Extratos Anti-inflamatórios'], '02 Cápsulas ao dia', ARRAY['Previne contra trombose', 'Melhora a musculatura', 'Auxilia na redução de inflamações', 'Indicado para Artrite, Artrose e Dores nas Articulações'], ARRAY[], 'Alívio nas articulações e força nos músculos. Vida sem dor. 60 cápsulas de 600mg.', 134.90, 150, true, NULL, ARRAY['articulacoes', 'artrite', 'artrose', 'dor']),
  
  ('COLAGENO_TIPO_II', 'Colágeno Tipo II', 'Nema''s Way', 'articulacoes', ARRAY['Colágeno Tipo II', 'Vitamina E'], '01 comprimido ao dia', ARRAY['Melhora a musculatura', 'Auxilia na redução de inflamações', 'Melhora a saúde óssea', 'Auxilia no tratamento de lesões e cartilagens', 'Auxilia no tratamento de Artrite Reumatoide'], ARRAY['Alergia a proteínas'], 'Aumente a elasticidade das articulações. Fortalece músculos e ossos, reduz inflamações e trata lesões. 30 comprimidos de 500mg.', 119.90, 120, true, NULL, ARRAY['colageno_tipo_ii', 'articulacoes', 'cartilagem', 'artrite']),
  
  ('OLEO_PRIMULA', 'Óleo de Prímula', 'Nema''s Way', 'saude_feminina', ARRAY['Óleo de Prímula 500mg'], '02 Cápsulas ao dia', ARRAY['Fortalece sistema imunológico', 'Auxilia na perda de peso', 'Combate má digestão', 'Promove saúde da pele'], ARRAY[], 'Saúde para o corpo. Parceiro na busca por vida saudável. 60 cápsulas de 500mg.', 119.90, 160, true, NULL, ARRAY['oleo_primula', 'feminino', 'hormonal', 'pele']),
  
  ('GOLD_MONEY', 'Gold Money', 'Nema''s Way', 'perfumaria', ARRAY[], 'Uso pessoal', ARRAY['Fragrância masculina elegante'], ARRAY[], 'Desafie as probabilidades. Supere os limites. Com Gold Money, você é invencível. Inspirado no Ferrari Black. 100ml.', 199.99, 100, true, NULL, ARRAY['perfume', 'masculino', 'fragrancia']),
  
  ('LIBWAY', 'LibWay', 'Nema''s Way', 'saude_sexual', ARRAY['Boro', 'Aspartato', 'Arginina', 'Taurina'], '01 Cápsula ao dia', ARRAY['Aumento dos hormônios', 'Melhora do desempenho sexual', 'Contribui no aumento da libido'], ARRAY['Câncer de próstata'], 'Sua confiança de volta, sua potência garantida. 30 cápsulas soft gel de 760mg.', 149.90, 130, true, NULL, ARRAY['libido', 'sexual', 'hormonal', 'vitalidade']),
  
  ('BVB_B12_350MG', 'BVB B12', 'Nema''s Way', 'vitaminas', ARRAY['Metilcobalamina 350mg'], '02 Cápsulas ao dia', ARRAY['Previne problemas cardíacos e derrame cerebral', 'Prevenção de doenças como Alzheimer', 'Melhor oxigenação no corpo', 'Produção de energia', 'Manutenção do sistema nervoso'], ARRAY['Alergia a cobalamina'], 'Energia para a mente e o corpo. Vital para saúde geral, produção de energia e manutenção do sistema nervoso. 60 cápsulas.', 149.90, 220, true, NULL, ARRAY['b12', 'energia', 'memoria', 'neurologico']),
  
  ('BVB_INSU', 'BVB Insu', 'Nema''s Way', 'metabolismo', ARRAY['Berberina', 'Cromo', 'Ácido Alfa-Lipóico'], '02 Cápsulas ao dia', ARRAY['Diminui Colesterol "Ruim" (LDL) e Triglicerídeos', 'Auxilia no tratamento da Diabetes ou Resistência à Insulina', 'Diminui fome e compulsão alimentar por doces', 'Mantém saúde da pele e cabelos'], ARRAY['Gravidez', 'Lactação', 'Hipoglicemia'], 'Caminho para equilíbrio e bem-estar. Trata problemas como colesterol e diabetes. 60 cápsulas de 700mg.', 149.90, 150, true, NULL, ARRAY['diabetes', 'colesterol', 'glicemia', 'insulina']),
  
  ('VITAMIX_SKIN', 'VitamixSkin', 'Nema''s Way', 'beleza', ARRAY['Vitaminas A, C, E', 'Zinco', 'Selênio'], '02 Cápsulas ao dia', ARRAY['Melhora elasticidade da pele', 'Reduz linhas de expressão', 'Regeneração das células'], ARRAY[], 'Cuide da sua pele do jeito que ela merece. Mantém pele saudável, firme e protegida contra envelhecimento precoce. 60 cápsulas de 310mg.', 109.90, 160, true, NULL, ARRAY['pele', 'vitaminas', 'antioxidante', 'elasticidade']),
  
  ('ACIDO_HIALURONICO_FITIOS', 'Ácido Hialurônico', 'Nema''s Way', 'beleza', ARRAY['Ácido Hialurônico', 'Vitamina B5', 'Vitamina C'], '01 Cápsula ao dia', ARRAY['Melhora elasticidade da pele', 'Reduz linhas de expressão', 'Regeneração das células', 'Combate flacidez'], ARRAY[], 'Refaz o que o tempo desfaz! Diga adeus à flacidez e recupere elasticidade da pele. 30 comprimidos de 800mg.', 99.90, 150, true, NULL, ARRAY['acido_hialuronico', 'pele', 'elasticidade', 'rugas']),
  
  ('OMEGA_3_1400MG', 'Ômega 3', 'Nema''s Way', 'cardiovascular', ARRAY['EPA 540mg', 'DHA 360mg'], '02 Cápsulas ao dia', ARRAY['Prevenção do Parkinson e Alzheimer', 'Auxilia na Depressão e Doenças Cardiovasculares', 'Controle da Pressão Arterial', 'Ação Anti-inflamatória e Efeito Antitrombótico'], ARRAY['Alergia a peixes', 'Uso de anticoagulantes'], 'Produto indicado para toda família. DHA 360 / EPA 540. 60 cápsulas de 1.400mg.', 129.99, 200, true, NULL, ARRAY['omega3', 'cardiovascular', 'cerebro', 'antiinflamatorio']),
  
  ('VIP_GLAMOUR_KIT', 'VIP Glamour Kit', 'Nema''s Way', 'beleza', ARRAY['Ativos naturais'], 'Uso Diário', ARRAY['Sensação de bem-estar', 'Sensação refrescante', 'Charme e sofisticação'], ARRAY[], 'Body Splash Corporal + Creme Corporal. Charme e sofisticação por onde passar. Inspirado no Vip Rose da Victoria''s Secret. 250ml cada.', 149.90, 120, true, NULL, ARRAY['cosmetico', 'body_splash', 'creme', 'fragrancia']),
  
  ('FAIR_WAY', 'Fair Way Ozonizado', 'Nema''s Way', 'beleza', ARRAY['Ozônio', 'Colágeno', 'Elastina'], 'Uso Diário', ARRAY['Estimulação da circulação sanguínea', 'Ação antioxidante', 'Hidratação profunda', 'Combate flacidez'], ARRAY[], 'Loção hidratante para o corpo. Combina poder do colágeno e elastina para pele mais firme, elástica e rejuvenescida. 200g.', 99.99, 170, true, NULL, ARRAY['loção_corporal', 'ozonizado', 'colageno', 'elastina']),
  
  ('BVB_ZINCO_QUELATO', 'BVB Zinco Quelato', 'Nema''s Way', 'minerais', ARRAY['Zinco Quelato 600mg'], '2 cápsulas (1 hora antes café, 1 hora antes almoço)', ARRAY['Ação antioxidante', 'Saúde da pele, cabelo e unhas', 'Fortalecimento do sistema imunológico', 'Suporte à visão', 'Manutenção da saúde óssea', 'Metabolismo otimizado'], ARRAY[], 'Sua imunidade merece mais. Forma de zinco de alta biodisponibilidade para máxima absorção. 60 cápsulas de 600mg.', 129.90, 220, true, NULL, ARRAY['zinco', 'imunidade', 'pele', 'quelato']),
  
  ('AMARGO', 'Amargo', 'Nema''s Way', 'digestao', ARRAY['Extrato de Alcachofra', 'Quassia', 'Quina', 'Salsaparrilha', 'Camomila', 'Carqueja', 'Chá Verde', 'Hortelã', 'Berinjela'], '02 colheres de sopa ao dia', ARRAY['Promove organismo mais eficiente', 'Elimina azia e desconfortos digestivos', 'Ajuda a reduzir acúmulo de gordura no fígado', 'Contribui para perda de peso'], ARRAY[], 'Ele é Amargo, mas é Bom! Transforme seu organismo em máquina funcional. Chá com Vegetal. 500ml.', 99.90, 180, true, NULL, ARRAY['digestao', 'figado', 'amargo', 'bile']),
  
  ('TOP_SECRETS', 'TOP Secrets Creme Clareador', 'Nema''s Way', 'beleza', ARRAY['Pantenol', 'Extrato de Ylang Ylang', 'Rosa Mosqueta'], '02 aplicações ao dia', ARRAY['Clareamento da pele', 'Hidratação profunda', 'Efeito rejuvenescedor', 'Suporte na cicatrização e regeneração'], ARRAY[], 'Segredo para pele mais clara e saudável. Para mãos e rosto. Ozonizado. 100g.', 99.90, 150, true, NULL, ARRAY['clareador', 'pele', 'rosa_mosqueta', 'ozonizado']),
  
  ('PEELING_5X1', 'Peeling 5X1', 'Nema''s Way', 'beleza', ARRAY['Vitamina E', 'Ácidos de Frutas'], '03 aplicações durante a semana', ARRAY['Limpa, Tonifica, Amacia, Hidrata, Clareia', 'Prevenção de rugas', 'Remove células mortas', 'Ação antioxidante'], ARRAY[], 'Corpo e Rosto. Sua pele incrivelmente renovada. Com Vitamina E. 145g.', 99.90, 150, true, NULL, ARRAY['peeling', 'esfoliante', 'gomage', 'renovacao']),
  
  ('SEREMIX', 'Seremix', 'Nema''s Way', 'sono', ARRAY['L-Triptofano 500mg', 'Melatonina', 'Magnésio'], '02 Cápsulas ao dia', ARRAY['Promove relaxamento', 'Promove melhor qualidade de sono', 'Alivia estresse'], ARRAY['Gravidez', 'Lactação'], 'Aliado para melhor noite de sono. Suplemento revolucionário para equilíbrio do organismo e sono. 60 cápsulas de 500mg.', 149.90, 200, true, NULL, ARRAY['sono', 'triptofano', 'relaxamento', 'ansiedade']),
  
  ('BVB_MORO', 'BVB Moro', 'Nema''s Way', 'emagrecimento', ARRAY['Extrato de Moro'], '2 cápsulas 30 minutos antes do almoço', ARRAY['Auxilia no controle e redução da gordura abdominal', 'Melhora metabolismo de carboidratos e lipídios', 'Regula glicemia e picos de insulina', 'Aumenta saciedade', 'Ação antioxidante (envelhecimento precoce)', 'Estimula corpo a usar gordura como energia'], ARRAY[], 'Transforme seu metabolismo em máquina de queimar gorduras. Mais energia, mais foco, mais definição. 60 cápsulas de 600mg.', 129.90, 140, true, NULL, ARRAY['emagrecimento', 'moro', 'metabolismo', 'gordura']),
  
  ('PROWOMAN', 'ProWoman', 'Nema''s Way', 'saude_feminina', ARRAY['Fitoestrógenos', 'Óleo de Prímula', 'Vitaminas do Complexo B'], '02 Cápsulas ao dia', ARRAY['Alivia sintomas da menopausa', 'Reduz risco de câncer de mama', 'Equilibra níveis hormonais'], ARRAY['Câncer hormônio-dependente'], 'Você Radiante e Forte Sempre. Suplemento especialmente formulado para necessidades das mulheres modernas. 60 cápsulas de 500mg.', 149.90, 150, true, NULL, ARRAY['feminino', 'menopausa', 'hormonal', 'cancer']),
  
  ('SERUM_VITAMINA_C', 'Sérum Vitamina C Ozonizado', 'Nema''s Way', 'beleza', ARRAY['Vitamina C', 'Vitamina E', 'Ácido Hialurônico', 'Colágeno'], 'Uso diário', ARRAY['Neutraliza radicais livres', 'Reduz inflamação e acalma a pele', 'Clareia manchas escuras', 'Estimula produção de colágeno'], ARRAY[], 'Para pele radiante e protegida todos os dias. Antioxidante poderoso que combate radicais livres e estimula colágeno. 20ml.', 119.99, 140, true, NULL, ARRAY['serum', 'vitamina_c', 'ozonizado', 'pele']),
  
  ('ORGANIC_OZON3_ARGAN', 'Organic Ozon3 Óleo de Argan', 'Nema''s Way', 'beleza', ARRAY['Óleo de Argan', 'Ozônio', 'Ácidos Graxos', 'Vitamina E'], 'Uso Diário', ARRAY['Reparação de cabelos danificados', 'Hidratação profunda', 'Ação antioxidante'], ARRAY[], 'Orgânico com Ozônio. Cuidado profundo, brilho intenso. Hidrata profundamente, restaura brilho e fortalece fios. 30ml.', 99.90, 150, true, NULL, ARRAY['argan', 'cabelo', 'ozonizado', 'organico']),
  
  ('POLIVITAMIX', 'Polivitamix', 'Nema''s Way', 'vitaminas', ARRAY['Complexo A-Z de Vitaminas e Minerais', 'Ômega 3 (MEG-3)'], '02 Cápsulas ao dia', ARRAY['Fortalece Sistema Imunológico', 'Regula Metabolismo', 'Energia e Vitalidade (combate fadiga)', 'Saúde Óssea e Mental'], ARRAY['Hipervitaminose'], 'Agora com Ômega 3. Segredo para vida mais saudável e ativa. Fornece mais energia e saúde. 60 cápsulas de 700mg.', 109.90, 200, true, NULL, ARRAY['multivitaminico', 'omega3', 'a-z', 'energia']),
  
  ('LIFE_WAY_GEL', 'Life Way Gel Massageador Ozonizado', 'Nema''s Way', 'topico', ARRAY['Mentol', 'Cânfora', 'Centella Asiática', 'Chá Verde', 'Alecrim', 'Óleo de Girassol Ozonizado'], 'Uso Diário', ARRAY['Alívio imediato de dores musculares', 'Sensação de relaxamento e bem-estar', 'Pele tonificada e suave', 'Alívio muscular'], ARRAY[], 'Chega de conviver com dores. Promove frescor, relaxamento e cuidado com a pele, aliviando tensões musculares. 150g.', 139.90, 160, true, NULL, ARRAY['gel_massageador', 'dor_muscular', 'ozonizado', 'relaxamento']),
  
  ('VISION_WAY', 'VisionWay', 'Nema''s Way', 'saude_ocular', ARRAY['Luteína', 'Zeaxantina', 'DHA', 'Óleo de Cártamo'], '01 Cápsula ao dia', ARRAY['Redução da síndrome de olho seco', 'Prevenção de inflamações oculares', 'Melhora da circulação ocular', 'Proteção contra luz azul e UV'], ARRAY[], 'Proteção avançada, visão clara. Filtra luz azul e protege contra raios UV. 30 cápsulas soft gel de 750mg.', 149.90, 100, true, NULL, ARRAY['visao', 'luteina', 'zeaxantina', 'olhos']),
  
  ('BVB_Q10', 'BVB Q10', 'Nema''s Way', 'energia', ARRAY['Coenzima Q10 700mg'], '01 Cápsula ao dia', ARRAY['Produção de energia', 'Contribui a melhorar fertilidade', 'Diminui chances de doenças cardiovasculares', 'Proteção antioxidante', 'Função neurológica'], ARRAY['Uso de varfarina'], 'Suporte completo para vida equilibrada. Essencial para produção de energia, saúde cardiovascular e proteção antioxidante. 30 cápsulas de 700mg.', 159.90, 120, true, NULL, ARRAY['coq10', 'energia', 'cardiovascular', 'fertilidade']),
  
  ('SABONETE_INTIMO_SEDUCAO', 'Sabonete Íntimo Sedução', 'Nema''s Way', 'higiene', ARRAY['Morango', 'Malva', 'Barbatimão'], 'Uso diário', ARRAY['Mantém PH equilibrado', 'Estimula processo imunológico', 'Auxilia no processo da Candidíase', 'Previne doenças ginecológicas'], ARRAY[], 'Nova fórmula. Sabonete íntimo incrível desenvolvido com cuidado que sua saúde íntima merece. pH neutro. 200ml.', 59.90, 200, true, NULL, ARRAY['sabonete_intimo', 'feminino', 'ph', 'candidíase']),
  
  ('TENIS_BIOQUANTICO', 'Tênis Bioquântico', 'Nema''s Way', 'equipamento', ARRAY['Íons magnéticos', 'Infravermelho longo', 'Tecido inteligente'], 'Uso diário', ARRAY['Alivia dores na coluna', 'Correção de postura', 'Bem estar e conforto'], ARRAY[], 'Caminhar com saúde, tecnologia e conforto. Íons magnéticos, infravermelho longo, palmilha que se ajusta. 1 par.', 1099.99, 50, true, NULL, ARRAY['tenis', 'bioquantico', 'postura', 'coluna']),
  
  ('MELATONINA', 'Melatonina', 'Nema''s Way', 'sono', ARRAY['Melatonina'], '2 cápsulas 30 minutos antes de dormir', ARRAY['Auxilia no início do sono', 'Melhora qualidade do sono (ciclos completos)', 'Promove relaxamento físico e mental', 'Auxilia em quadros de insônia leve e jet lag', 'Contribui para equilíbrio hormonal'], ARRAY['Gravidez', 'Lactação', 'Doenças autoimunes'], 'Durma profundamente e acorde renovado. Aliado para noites completas e restauradoras. 60 cápsulas de 600mg.', 99.90, 280, true, NULL, ARRAY['melatonina', 'sono', 'insonia', 'relaxamento']),
  
  ('CREATINA_Q10', 'Creatina com Coenzima Q10', 'Nema''s Way', 'performance', ARRAY['Creatina Monohidratada 3g', 'Coenzima Q10'], 'Diluir 3g (1 scoop) em 150ml de água', ARRAY['Mais energia e resistência física', 'Foco mental e desempenho cognitivo', 'Saúde do coração', 'Ação antioxidante e antienvelhecimento', 'Combate cansaço crônico'], ARRAY['Problemas renais'], 'Corpo em forma, mente em equilíbrio. Creatina 100% pura com Coenzima Q10. 300g.', 299.99, 200, true, NULL, ARRAY['creatina', 'coq10', 'performance', 'energia']),
  
  ('KIT_ORGANIC_OZON3', 'Kit Organic Ozon3 Shampoo + Alinhamento', 'Nema''s Way', 'beleza', ARRAY['Óleo de Argan', 'Tanino', 'Ozônio'], 'Aplicar por profissional cabeleireiro', ARRAY['Ação antioxidante e antibacteriana', 'Facilidade de manutenção', 'Redução do frizz'], ARRAY[], 'Cabelos lisos, leves e radiantes. 0% Formol. Alisa, nutre profundamente, repara danos e revitaliza. 550ml cada.', 399.90, 80, true, NULL, ARRAY['cabelo', 'alinhamento', 'ozonizado', 'kit']),
  
  ('SERUM_RETINOL', 'Sérum Retinol Ozonizado', 'Nema''s Way', 'beleza', ARRAY['Retinol', 'Vitamina E', 'Ácido Hialurônico', 'Colágeno'], 'Uso diário', ARRAY['Protege pele de radicais livres', 'Reduz sinais de envelhecimento (rugas/linhas)', 'Promove elasticidade e firmeza'], ARRAY['Gravidez', 'Lactação'], 'Revitalize sua pele com poder do Retinol e pureza do Ozônio. Reduz rugas e linhas finas. 20ml.', 119.99, 130, true, NULL, ARRAY['retinol', 'anti_idade', 'ozonizado', 'pele']),
  
  ('SD_FIBRO3', 'SD Fibro3 com Cúrcuma', 'Nema''s Way', 'antiinflamatorios', ARRAY['Magnésio Quelato', 'Dimagnésio Malato', 'Taurato de Magnésio', 'Cúrcuma'], '02 Cápsulas ao dia', ARRAY['Combate dores da Fibromialgia e Osteoporose', 'Adeus Enxaqueca e Alívio da Asma', 'Melhora saúde cardiovascular, sistema nervoso, óssea e intestinal'], ARRAY['Obstrução das vias biliares'], 'Para uma vida sem dor. Fusão poderosa de três tipos de magnésio com cúrcuma. 60 cápsulas de 600mg.', 149.90, 180, true, NULL, ARRAY['fibromialgia', 'magnesio', 'curcuma', 'dor']),
  
  ('SPIRULINA_VIT_E', 'Spirulina + Vitamina E', 'Nema''s Way', 'superalimentos', ARRAY['Spirulina platensis 1000mg', 'Vitamina E'], '03 Comprimidos ao dia', ARRAY['Age como poderoso antioxidante', 'Ação Anti-inflamatória', 'Colabora para flora intestinal saudável', 'Reduz sintomas do cansaço'], ARRAY['Fenilcetonúria'], 'Limpeza completa para seu organismo. Potencialize sua saúde. 90 comprimidos de 1000mg cada.', 139.90, 250, true, NULL, ARRAY['spirulina', 'vitamina_e', 'desintoxicacao', 'antioxidante']),
  
  ('OLEO_GIRASSOL_OZONIZADO', 'Óleo de Girassol Ozonizado', 'Nema''s Way', 'topico', ARRAY['Óleo de Girassol Ozonizado'], '02 aplicações ao dia', ARRAY['Combate Acnes, Rugas e promove Renovação Celular', 'Hidratação anti-idade', 'Alto poder de cicatrização (queimaduras)', 'Ação antioxidante, antimicrobiana', 'Alívio para Psoríase'], ARRAY[], 'Tecnologia avançada para cicatrização eficaz. Manchas, acnes ou qualquer problema de pele não serão mais problema. 30ml.', 109.90, 150, true, NULL, ARRAY['oleo_girassol', 'ozonizado', 'cicatrizacao', 'pele']),
  
  ('OLEO_REGENERADOR', 'Óleo Regenerador Ozonizado', 'Nema''s Way', 'beleza', ARRAY['Rosa Mosqueta', 'Semente de Uva', 'Copaíba', 'Girassol Extra Virgem'], 'Diariamente a noite', ARRAY['Promove regeneração celular', 'Reduz rugas e linhas finas', 'Rica em antioxidantes', 'Redução de cicatrizes e manchas'], ARRAY[], 'Transformação começa em cada gota. Sinfonia natural de ingredientes preciosos. Elixir de rejuvenescimento. 30ml.', 109.90, 140, true, NULL, ARRAY['oleo_regenerador', 'rosa_mosqueta', 'ozonizado', 'anti_idade']),
  
  ('GEL_CRIOTERAPICO', 'Gel Crioterápico', 'Nema''s Way', 'topico', ARRAY['Cafeína', 'Centella Asiática', 'Alga Fucus', 'Mentol', 'Colágeno'], 'Uso diário', ARRAY['Redução de Gordura Localizada', 'Modelagem do contorno corporal', 'Ação drenante (inchaço)', 'Melhora textura da pele (celulite)'], ARRAY[], 'Seu corpo, sua regra: sem espaço para pneuzinhos. Solução high-performance para redução de medidas. 500g.', 99.90, 180, true, NULL, ARRAY['gel_crioterapico', 'gordura_localizada', 'celulite', 'drenante']),
  
  ('FOCUS_TDAH', 'Focus TDAH Premium', 'Nema''s Way', 'cognicao', ARRAY['Ingredientes para foco e concentração'], '02 Cápsulas ao dia', ARRAY['Melhora do foco e concentração', 'Redução do estresse e ansiedade', 'Melhora do humor e bem-estar', 'Proteção do sistema nervoso', 'Redução da fadiga mental'], ARRAY[], 'Foco, clareza e equilíbrio para sua mente. Aumenta concentração, reduz fadiga mental e melhora produtividade. 60 cápsulas de 500mg.', 159.90, 150, true, NULL, ARRAY['foco', 'concentracao', 'tdah', 'cognicao']),
  
  ('CAR_BLACK', 'Car Black', 'Nema''s Way', 'perfumaria', ARRAY[], 'Uso pessoal', ARRAY['Fragrância masculina elegante'], ARRAY[], 'Desafie as probabilidades. Supere os limites. Inspirado no Ferrari Black. 100ml.', 199.99, 100, true, NULL, ARRAY['perfume', 'masculino', 'fragrancia']),
  
  ('MADAME_X', 'Madame X', 'Nema''s Way', 'perfumaria', ARRAY[], 'Uso pessoal', ARRAY['Fragrância feminina sofisticada'], ARRAY[], 'Descubra sua singularidade. Inspirada no Coco Mademoiselle. Revele sua autenticidade. 100ml.', 199.99, 100, true, NULL, ARRAY['perfume', 'feminino', 'fragrancia']),
  
  ('MOLECULA_DA_VIDA', 'Molécula da Vida', 'Nema''s Way', 'digestao', ARRAY['Ácido Araquidônico'], '02 Cápsulas ao dia', ARRAY['Melhora da saúde digestiva e mucosa intestinal', 'Alívio de gastrite, úlceras e desconfortos', 'Ação anti-inflamatória natural potente', 'Proteção contra bactéria H. pylori', 'Promoção do equilíbrio intestinal'], ARRAY[], 'Cuide do sistema digestivo de forma natural e eficaz. Ação anti-inflamatória e protetora. 60 cápsulas de 300mg.', 159.99, 150, true, NULL, ARRAY['digestao', 'gastrite', 'h_pylori', 'antiinflamatorio']),
  
  ('MEGA_NUTRI_RX21', 'Mega Nutri RX21', 'Nema''s Way', 'beleza', ARRAY['Vitaminas e Minerais'], '01 Comprimido ao dia', ARRAY['Reduz a queda capilar', 'Fortalece e aumenta elasticidade dos fios', 'Promove unhas saudáveis e menos quebradiças', 'Estimula crescimento'], ARRAY[], 'Tratamento para Cabelo, Pele e Unhas. Solução completa para fortalecer e cuidar da beleza. 30 comprimidos de 800mg.', 99.90, 150, true, NULL, ARRAY['cabelo', 'unhas', 'pele', 'vitaminas']),
  
  ('OLEO_MASSAGEM_OZONIZADO', 'Óleo de Massagem Ozonizado', 'Nema''s Way', 'topico', ARRAY['Arnica', 'Óleo de Girassol Ozonizado'], 'Uso diário', ARRAY['Tratamento eficaz para hematomas', 'Promove relaxamento muscular e alivia tensões', 'Auxilia no tratamento de varizes', 'Ativa articulações e melhora circulação'], ARRAY[], 'Tratamento para corpo inteiro. Solução completa para bem-estar. Fórmula potente para todas as dores. 120ml.', 99.90, 160, true, NULL, ARRAY['oleo_massagem', 'arnica', 'ozonizado', 'varizes']),
  
  ('PROPOLIS_VERDE', 'Própolis Verde', 'Nema''s Way', 'imunidade', ARRAY['Própolis Verde 300mg'], '02 Cápsulas ao dia', ARRAY['Reforça Sistema Imunológico (infecções bacterianas, fúngicas, virais)', 'Acelera cicatrização de feridas (incluindo queimaduras)', 'Alivia desconfortos (Faringite, Amigdalite, Gripes)', 'Promove saúde geral'], ARRAY['Alergia a própolis'], 'Imunidade imediata em uma única cápsula. Fórmula poderosa que combate infecções e acelera cicatrização. 60 cápsulas de 300mg.', 139.90, 180, true, NULL, ARRAY['propolis_verde', 'imunidade', 'antimicrobiano', 'cicatrizacao']),
  
  ('PROPOWAY_VERMELHA', 'PropoWay Vermelha', 'Nema''s Way', 'imunidade', ARRAY['Extrato de Própolis', 'Óleo de Linhaça', 'TCM'], '02 Cápsulas ao dia', ARRAY['Auxilia no fortalecimento do sistema imunológico', 'Previne cáries e gengivites', 'Auxilia na recuperação de feridas e lesões na pele'], ARRAY['Alergia a própolis'], 'Imunidade e Resistência em Duas Cápsulas! Fortalece sistema imunológico e melhora saúde cardiovascular. 60 cápsulas de 300mg.', 139.90, 170, true, NULL, ARRAY['propolis_vermelha', 'imunidade', 'cardiovascular', 'energia']),
  
  ('PROMEN', 'Promen', 'Nema''s Way', 'saude_geral', ARRAY['Lycopene', 'Óleo de Semente de Uva', 'Óleo de Abóbora', 'Vitamina E'], '02 Cápsulas ao dia', ARRAY['Prevenção do Infarto e AVC', 'Auxilia na Prevenção do Câncer de Próstata, Colo do Útero, Mamas', 'Fortalecimento do Sistema Imunológico', 'Melhora da Fertilidade Masculina', 'Trata Hiperplasia Benigna da Próstata'], ARRAY['Insuficiência cardíaca'], 'Tratamento para Homens e Mulheres. Vida de qualidade e bem-estar. 60 cápsulas de 1.400mg.', 149.90, 150, true, NULL, ARRAY['prostata', 'cancer', 'cardiovascular', 'fertilidade'])

ON CONFLICT (external_id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    active_ingredients = EXCLUDED.active_ingredients,
    recommended_dosage = EXCLUDED.recommended_dosage,
    benefits = EXCLUDED.benefits,
    contraindications = EXCLUDED.contraindications,
    description = EXCLUDED.description,
    original_price = EXCLUDED.original_price,
    discount_price = ROUND(EXCLUDED.original_price * 0.5, 2), -- 50% de desconto automático
    stock_quantity = EXCLUDED.stock_quantity,
    image_url = EXCLUDED.image_url,
    tags = EXCLUDED.tags,
    updated_at = NOW();

